##logging:
##  level:
##    org:
##      springframework: DEBUG
#
#
#spring:
#  datasource:
#    username:
#    password:
#    # url: jdbc:h2:mem:ride_tracker
#
#  h2:
#    console:
#      enable: true
#      path: /h2
#
#  jpa:
#    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        jdbc:
#          lob:
#            non_contextual_creation: true
#
#    hibernate:
#      ddl-auto: none
#      show-sql: true
