#app:
#  version: 0.1.0
#
#server:
#  port: 5000
#
#
#spring:
#  profiles:
#    active: dev
#
#  thymeleaf:
#    template-loader-path=classpath: /templates
#    suffix: .html
#    cache: false
#
#  h2:
#    console:
#      enable: true
#      path: /h2
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: info,health,metrics,loggers,beans,mappings
#
#  endpoint:
#    health:
#      show-details: always
